# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: queue.proto for package 'songrequest'

require 'grpc'
require 'queue_pb'

module Songrequest
  module Queue
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'songrequest.Queue'

      rpc :GetNextSong, ::Songrequest::GetNextSongRequest, ::Songrequest::GetNextSongResponse
      rpc :ListSongs, ::Songrequest::ListSongsRequest, ::Songrequest::ListSongsResponse
      rpc :AddSong, ::Songrequest::Song, ::Songrequest::ListSongsResponse
    end

    Stub = Service.rpc_stub_class
  end
end
