# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: queue.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("queue.proto", :syntax => :proto3) do
    add_message "songrequest.GetNextSongRequest" do
    end
    add_message "songrequest.GetNextSongResponse" do
      optional :song, :message, 1, "songrequest.Song"
    end
    add_message "songrequest.ListSongsRequest" do
    end
    add_message "songrequest.ListSongsResponse" do
      repeated :songs, :message, 1, "songrequest.Song"
    end
    add_message "songrequest.Song" do
      optional :requested_by, :string, 1
      optional :song_url, :string, 2
    end
  end
end

module Songrequest
  GetNextSongRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("songrequest.GetNextSongRequest").msgclass
  GetNextSongResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("songrequest.GetNextSongResponse").msgclass
  ListSongsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("songrequest.ListSongsRequest").msgclass
  ListSongsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("songrequest.ListSongsResponse").msgclass
  Song = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("songrequest.Song").msgclass
end
